## Numpy arrays and array attributes

In [1]:
import numpy as np

In [6]:
#array
array1d = np.array([1,2,3])
print(array1d.shape)

(3,)


In [12]:
#shape
array2d = np.array([[1,2,3],[5,6,7]])
print(array2d.dtype)

int64


In [11]:
#zeros
#size
zeros = np.zeros((5,3))
print(zeros.size)

15


In [13]:
ones = np.ones((4,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
arrange = np.arange(0,11,2)
print(arrange)

[ 0  2  4  6  8 10]


In [14]:
string = ['apple','banana','xyz123']
s = np.array(string)
print(s.dtype)

<U6


In [15]:
b = [True,False]
b = np.array(b)
print(b.dtype)

bool
