## Tutorial 3: Array Indexing and Slicing
Basic Indexing\
Accessing elements in arrays.\
Slicing Arrays\
Understanding slicing techniques to extract subarrays.\
Advanced Indexing\
Boolean indexing and fancy indexing.


In [11]:
import numpy as np


In [12]:
# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])
first_element = arr[0]  
print(first_element)

10


In [13]:
third_element = arr[2]
print(third_element)

30


In [15]:
# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)


# Access the element in the second row, third column
element = matrix[1, 2]
print(element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [16]:
#slicing array
#array[start:stop:step]

# Slice elements from index 1 to 4
subarray = arr[1:4] 
print(subarray)

[20 30 40]


In [18]:
# Slice every other element
every_other = arr[::2]
print(arr)
print(every_other)

[10 20 30 40 50]
[10 30 50]


In [19]:
last_two = arr[-2:] 
print(last_two)

[40 50]


In [21]:
# Slice the first two rows and the last two columns
submatrix = matrix[:2, -2:] 

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(submatrix)

[[2 3]
 [5 6]]


## Advanced Indexing


In [24]:
# Create a boolean array where elements are greater than 25
print(arr)
bool_idx = arr > 25
print(bool_idx)

[10 20 30 40 50]
[False False  True  True  True]


In [25]:
# Use boolean indexing to select elements
filtered_array = arr[bool_idx]
print(filtered_array)

[30 40 50]


In [27]:
# Indices of elements to access
indices = [0, 2, 4]

# Use fancy indexing
selected_elements = arr[indices] 
# print(arr)
print(selected_elements)

[10 30 50]
